-- Typed Delta tables for the Control Tower Genie Agent workshop.
-- ALL DATA IS SYNTHETIC. Generated by data/generate_banking_data.py (seed=7).
--
-- Every table and every column carries a COMMENT. This is deliberate and it is the
-- single highest-leverage accuracy lever: per the Production-Grade Genie Field Guide,
-- "hallucinated column names -> columns not described -> add column descriptions".
-- Comments are written in the business vocabulary a banker would actually use, and
-- spell out units (INR, days, percent) because Genie cannot infer them.


-- ===========================================================================
-- SHARED DIMENSIONS
-- ===========================================================================

CREATE OR REPLACE TABLE branch_master AS
SELECT * FROM read_files(
  '/Volumes/${CATALOG}/${SCHEMA}//seed/branch_master.csv',
  format => 'csv', header => true, inferSchema => true);

COMMENT ON TABLE branch_master IS
  'Branch dimension. One row per bank branch. Join key for every fact table in this schema. 18 synthetic branches across 6 regions.';
ALTER TABLE branch_master ALTER COLUMN branch_id COMMENT 'Branch code, primary key. Format BRnnn. Join to any fact table on branch_id.';
ALTER TABLE branch_master ALTER COLUMN branch_name COMMENT 'Human-readable branch name, e.g. "Solapur Rural".';
ALTER TABLE branch_master ALTER COLUMN city COMMENT 'City the branch is located in. Solapur and Indore are the two cities carrying stress in this dataset.';
ALTER TABLE branch_master ALTER COLUMN state COMMENT 'Indian state, e.g. Maharashtra, Madhya Pradesh.';
ALTER TABLE branch_master ALTER COLUMN region COMMENT 'Sales region. One of North, South, East, West, Central. Use this for regional roll-ups.';
ALTER TABLE branch_master ALTER COLUMN zone COMMENT 'Branch classification: Metro, Urban, Semi-Urban, or Rural. Rural and Semi-Urban carry most microfinance exposure.';
ALTER TABLE branch_master ALTER COLUMN opened_date COMMENT 'Date the branch opened.';
ALTER TABLE branch_master ALTER COLUMN employee_count COMMENT 'Number of staff at the branch.';

CREATE OR REPLACE TABLE product_master AS
SELECT * FROM read_files(
  '/Volumes/${CATALOG}/${SCHEMA}//seed/product_master.csv',
  format => 'csv', header => true, inferSchema => true);

COMMENT ON TABLE product_master IS
  'Lending and card product dimension. Join on product_code. Segment groups products into the bank business lines.';
ALTER TABLE product_master ALTER COLUMN product_code COMMENT 'Product code, primary key. CV=Commercial Vehicle, PV=Passenger Vehicle, TW=Two Wheeler, MFI=Microfinance Group Loan, PL=Personal Loan, CC=Credit Card, HL=Home Loan, BL=Business Loan.';
ALTER TABLE product_master ALTER COLUMN product_name COMMENT 'Full product name.';
ALTER TABLE product_master ALTER COLUMN segment COMMENT 'Business line: Vehicle Finance, Microfinance, Retail Unsecured, Cards, Mortgages, Business Banking.';
ALTER TABLE product_master ALTER COLUMN is_secured COMMENT 'TRUE when the loan is secured by collateral. Microfinance, personal loans, cards and business loans are unsecured.';

-- ===========================================================================
-- COLLECTIONS AND RECOVERY  (Genie agent 1)
-- ===========================================================================

CREATE OR REPLACE TABLE loan_accounts AS
SELECT * FROM read_files(
  '/Volumes/${CATALOG}/${SCHEMA}//seed/loan_accounts.csv',
  format => 'csv', header => true, inferSchema => true);

COMMENT ON TABLE loan_accounts IS
  'Loan account master. One row per loan account, 6,000 accounts. Current book position: use outstanding_principal, not sanctioned_amount, when asked about exposure or book size.';
ALTER TABLE loan_accounts ALTER COLUMN loan_account_id COMMENT 'Loan account number, primary key. Format LNnnnnnn.';
ALTER TABLE loan_accounts ALTER COLUMN customer_id COMMENT 'Customer identifier. Format CUnnnnnn. Join to customer_portfolio to reach the relationship manager.';
ALTER TABLE loan_accounts ALTER COLUMN product_code COMMENT 'Product code. Join to product_master. MFI is microfinance, CV is commercial vehicle.';
ALTER TABLE loan_accounts ALTER COLUMN branch_id COMMENT 'Originating branch. Join to branch_master.';
ALTER TABLE loan_accounts ALTER COLUMN disbursed_date COMMENT 'Date the loan was disbursed.';
ALTER TABLE loan_accounts ALTER COLUMN sanctioned_amount COMMENT 'Original sanctioned loan amount in INR. This is the amount approved at origination, NOT the current balance.';
ALTER TABLE loan_accounts ALTER COLUMN outstanding_principal COMMENT 'Current outstanding principal in INR. USE THIS for exposure, book size, and portfolio value questions.';
ALTER TABLE loan_accounts ALTER COLUMN interest_rate COMMENT 'Annual interest rate as a percentage, e.g. 23.5 means 23.5 percent per annum.';
ALTER TABLE loan_accounts ALTER COLUMN tenure_months COMMENT 'Loan tenure in months. Zero for revolving products such as credit cards.';
ALTER TABLE loan_accounts ALTER COLUMN emi_amount COMMENT 'Monthly instalment (EMI) in INR. Zero for revolving products.';
ALTER TABLE loan_accounts ALTER COLUMN customer_segment COMMENT 'Borrower segment, e.g. Rural Household (microfinance), Small Fleet Operator (commercial vehicle), Salaried, Self Employed, MSME.';
ALTER TABLE loan_accounts ALTER COLUMN is_restructured COMMENT 'TRUE when the loan has been restructured. Restructured accounts need separate treatment in delinquency analysis.';

CREATE OR REPLACE TABLE delinquency_monthly AS
SELECT * FROM read_files(
  '/Volumes/${CATALOG}/${SCHEMA}//seed/delinquency_monthly.csv',
  format => 'csv', header => true, inferSchema => true);

COMMENT ON TABLE delinquency_monthly IS
  'Month-end delinquency snapshot, one row per loan account per month, 18 months from 2025-03 to 2026-08. THIS IS THE PRIMARY TABLE for delinquency, DPD, bucket, NPA and roll-rate questions. Grain is snapshot_month x loan_account_id, so always aggregate rather than returning raw rows.';
ALTER TABLE delinquency_monthly ALTER COLUMN snapshot_month COMMENT 'Month-end snapshot date, always the first day of the month. The latest month in the data is 2026-08-01. Filter on this for point-in-time questions.';
ALTER TABLE delinquency_monthly ALTER COLUMN loan_account_id COMMENT 'Loan account number. Join to loan_accounts.';
ALTER TABLE delinquency_monthly ALTER COLUMN product_code COMMENT 'Product code, denormalised from loan_accounts so product filters need no join.';
ALTER TABLE delinquency_monthly ALTER COLUMN branch_id COMMENT 'Branch code, denormalised from loan_accounts so branch filters need no join.';
ALTER TABLE delinquency_monthly ALTER COLUMN dpd_days COMMENT 'Days past due at month end. Zero means the account is current and not delinquent.';
ALTER TABLE delinquency_monthly ALTER COLUMN dpd_bucket COMMENT 'Regulatory ageing bucket derived from dpd_days: "0-Current", "1-SMA0 (1-30)", "2-SMA1 (31-60)", "3-SMA2 (61-90)", "4-NPA (90+)". SMA means Special Mention Account. Use this for bucket-wise reporting.';
ALTER TABLE delinquency_monthly ALTER COLUMN outstanding_principal COMMENT 'Outstanding principal in INR at that snapshot.';
ALTER TABLE delinquency_monthly ALTER COLUMN overdue_amount COMMENT 'Amount overdue in INR at that snapshot. Zero when the account is current.';
ALTER TABLE delinquency_monthly ALTER COLUMN is_npa COMMENT 'TRUE when dpd_days is greater than 90, i.e. the account is a Non-Performing Asset. GNPA percentage is is_npa exposure divided by total exposure.';
ALTER TABLE delinquency_monthly ALTER COLUMN roll_direction COMMENT 'Bucket movement versus the previous month: "forward" means the account deteriorated into a worse bucket, "backward" means it improved, "stable" means unchanged. Roll-forward rate is the share of accounts with roll_direction = forward.';

CREATE OR REPLACE TABLE collections_activity AS
SELECT * FROM read_files(
  '/Volumes/${CATALOG}/${SCHEMA}//seed/collections_activity.csv',
  format => 'csv', header => true, inferSchema => true);

COMMENT ON TABLE collections_activity IS
  'Collections contact attempts by field and tele-calling agents. One row per contact attempt. Includes contact_hour and within_rbi_hours so RBI recovery-agent conduct rules can be audited: contact is only permitted between 08:00 and 19:00.';
ALTER TABLE collections_activity ALTER COLUMN activity_id COMMENT 'Activity identifier, primary key.';
ALTER TABLE collections_activity ALTER COLUMN activity_date COMMENT 'Date of the contact attempt.';
ALTER TABLE collections_activity ALTER COLUMN contact_hour COMMENT 'Hour of day of contact in 24-hour clock, e.g. 20 means 8pm. RBI permits borrower contact only between 08:00 and 19:00.';
ALTER TABLE collections_activity ALTER COLUMN loan_account_id COMMENT 'Loan account contacted. Join to loan_accounts.';
ALTER TABLE collections_activity ALTER COLUMN product_code COMMENT 'Product code, denormalised.';
ALTER TABLE collections_activity ALTER COLUMN branch_id COMMENT 'Branch code, denormalised.';
ALTER TABLE collections_activity ALTER COLUMN agent_id COMMENT 'Recovery agent who made contact. Join to recovery_agents to check RBI conduct certification.';
ALTER TABLE collections_activity ALTER COLUMN channel COMMENT 'Contact channel: Tele-calling, SMS, Field Visit, WhatsApp, Email, or Legal Notice.';
ALTER TABLE collections_activity ALTER COLUMN outcome COMMENT 'Result of contact. "Contacted - PTP" means the borrower gave a promise to pay. Other values: Contacted - Refused, Contacted - Disputed, Not Reachable, Wrong Number, Paid, Partial Payment.';
ALTER TABLE collections_activity ALTER COLUMN promise_to_pay_amount COMMENT 'Amount in INR the borrower promised to pay. Zero when no promise was given.';
ALTER TABLE collections_activity ALTER COLUMN amount_collected COMMENT 'Amount in INR actually collected during this contact. Zero when nothing was collected.';
ALTER TABLE collections_activity ALTER COLUMN within_rbi_hours COMMENT 'TRUE when contact_hour falls inside the RBI-permitted 08:00 to 19:00 window. FALSE indicates a potential conduct breach that must be investigated and reported.';

CREATE OR REPLACE TABLE recovery_agents AS
SELECT * FROM read_files(
  '/Volumes/${CATALOG}/${SCHEMA}//seed/recovery_agents.csv',
  format => 'csv', header => true, inferSchema => true);

COMMENT ON TABLE recovery_agents IS
  'Field recovery agents employed through collection agencies. Carries the RBI conduct-certification status that governs whether an agent may be assigned to a borrower visit.';
ALTER TABLE recovery_agents ALTER COLUMN agent_id COMMENT 'Recovery agent identifier, primary key. Format AGnnn.';
ALTER TABLE recovery_agents ALTER COLUMN agent_name COMMENT 'Agent full name.';
ALTER TABLE recovery_agents ALTER COLUMN agency_name COMMENT 'Collection agency employing the agent. Banks remain accountable for agency conduct under RBI rules.';
ALTER TABLE recovery_agents ALTER COLUMN branch_id COMMENT 'Branch the agent is mapped to.';
ALTER TABLE recovery_agents ALTER COLUMN region COMMENT 'Region the agent operates in.';
ALTER TABLE recovery_agents ALTER COLUMN rbi_conduct_certified COMMENT 'TRUE when the agent has completed mandatory RBI recovery-agent conduct training. An uncertified agent MUST NOT be assigned to a field visit.';
ALTER TABLE recovery_agents ALTER COLUMN certification_expiry COMMENT 'Date the conduct certification expires. A certification expiring before the visit date is treated as uncertified.';
ALTER TABLE recovery_agents ALTER COLUMN active_flag COMMENT 'TRUE when the agent is currently active.';
ALTER TABLE recovery_agents ALTER COLUMN complaints_against_ytd COMMENT 'Number of borrower complaints raised against this agent year to date. Agents with 3 or more complaints warrant review.';

CREATE OR REPLACE TABLE repayment_schedule AS
SELECT * FROM read_files(
  '/Volumes/${CATALOG}/${SCHEMA}//seed/repayment_schedule.csv',
  format => 'csv', header => true, inferSchema => true);

COMMENT ON TABLE repayment_schedule IS
  'Per-loan repayment position: next due date, instalments paid and pending, last payment, and mandate type. One row per amortising loan account.';
ALTER TABLE repayment_schedule ALTER COLUMN loan_account_id COMMENT 'Loan account number, primary key. Join to loan_accounts.';
ALTER TABLE repayment_schedule ALTER COLUMN product_code COMMENT 'Product code, denormalised.';
ALTER TABLE repayment_schedule ALTER COLUMN branch_id COMMENT 'Branch code, denormalised.';
ALTER TABLE repayment_schedule ALTER COLUMN next_due_date COMMENT 'Date the next instalment falls due. Use for "due this week" or upcoming-collection questions.';
ALTER TABLE repayment_schedule ALTER COLUMN emi_amount COMMENT 'Monthly instalment amount in INR.';
ALTER TABLE repayment_schedule ALTER COLUMN emis_paid COMMENT 'Count of instalments paid so far.';
ALTER TABLE repayment_schedule ALTER COLUMN emis_pending COMMENT 'Count of instalments still outstanding.';
ALTER TABLE repayment_schedule ALTER COLUMN last_payment_date COMMENT 'Date of the most recent payment received.';
ALTER TABLE repayment_schedule ALTER COLUMN last_payment_amount COMMENT 'Amount in INR of the most recent payment.';
ALTER TABLE repayment_schedule ALTER COLUMN mandate_type COMMENT 'Repayment mandate: NACH (auto-debit), Cheque, Cash, or UPI Autopay. NACH failures are a leading delinquency indicator.';

-- ===========================================================================
-- SERVICE AND GRIEVANCE  (Genie agent 2)
-- ===========================================================================

CREATE OR REPLACE TABLE complaint_categories AS
SELECT * FROM read_files(
  '/Volumes/${CATALOG}/${SCHEMA}//seed/complaint_categories.csv',
  format => 'csv', header => true, inferSchema => true);

COMMENT ON TABLE complaint_categories IS
  'Complaint category dimension mapping internal categories to RBI Integrated Ombudsman Scheme grounds, with the turnaround SLA in days for each.';
ALTER TABLE complaint_categories ALTER COLUMN category_code COMMENT 'Category code, primary key. UPI=UPI dispute, PAY=payment failure, CRD=card dispute, LON=loan servicing, DEP=deposit servicing, MIS=mis-selling, REC=recovery agent conduct, ATM=ATM/cash, KYC=KYC documentation, CHG=unauthorised charges.';
ALTER TABLE complaint_categories ALTER COLUMN category_name COMMENT 'Description of the complaint category.';
ALTER TABLE complaint_categories ALTER COLUMN rbi_category COMMENT 'RBI Integrated Ombudsman Scheme ground of complaint, e.g. "Payment systems", "Recovery agents", "Mis-selling", "Levy of charges". Use this for regulatory reporting roll-ups.';
ALTER TABLE complaint_categories ALTER COLUMN sla_days COMMENT 'Contractual turnaround SLA in calendar days for this category. A complaint resolved after this many days is an SLA breach.';

CREATE OR REPLACE TABLE complaints AS
SELECT * FROM read_files(
  '/Volumes/${CATALOG}/${SCHEMA}//seed/complaints.csv',
  format => 'csv', header => true, inferSchema => true);

COMMENT ON TABLE complaints IS
  'Customer complaints across all channels, 18 months. THIS IS THE PRIMARY TABLE for grievance, SLA, and ombudsman questions. Note the UPI complaint spike on 2026-06-16 to 2026-06-18, two days after a UPI switch degradation on 2026-06-14 and 15.';
ALTER TABLE complaints ALTER COLUMN complaint_id COMMENT 'Complaint reference, primary key. Format CMnnnnnnn.';
ALTER TABLE complaints ALTER COLUMN received_date COMMENT 'Date the complaint was received. Filter on this for volume-over-time questions.';
ALTER TABLE complaints ALTER COLUMN channel COMMENT 'Intake channel: Branch, Call Centre, Email, Mobile App, Website, RBI CMS, or Social Media. RBI CMS means the complaint arrived through the RBI Complaint Management System, which is a regulatory escalation.';
ALTER TABLE complaints ALTER COLUMN category_code COMMENT 'Complaint category. Join to complaint_categories for the RBI ground and the SLA.';
ALTER TABLE complaints ALTER COLUMN customer_id COMMENT 'Complaining customer. Join to customer_portfolio.';
ALTER TABLE complaints ALTER COLUMN branch_id COMMENT 'Branch the complaint is attributed to.';
ALTER TABLE complaints ALTER COLUMN product_code COMMENT 'Product the complaint relates to.';
ALTER TABLE complaints ALTER COLUMN severity COMMENT 'Assessed severity: Low, Medium, High, or Critical.';
ALTER TABLE complaints ALTER COLUMN status COMMENT 'Current state: Open, Resolved, or "Closed - No Deficiency". Open complaints have a NULL resolved_date.';
ALTER TABLE complaints ALTER COLUMN resolved_date COMMENT 'Date the complaint was resolved. NULL while the complaint is still open.';
ALTER TABLE complaints ALTER COLUMN days_to_resolve COMMENT 'Calendar days taken to resolve. NULL while still open.';
ALTER TABLE complaints ALTER COLUMN sla_days COMMENT 'The SLA in days that applied to this complaint, denormalised from complaint_categories.';
ALTER TABLE complaints ALTER COLUMN sla_breached COMMENT 'TRUE when the complaint took longer than sla_days to resolve, or is still open beyond its SLA. This is the headline regulatory metric.';
ALTER TABLE complaints ALTER COLUMN escalated_to_ombudsman COMMENT 'TRUE when the complaint was escalated to the RBI Ombudsman. Escalations are the most serious outcome and concentrate in recovery-agent conduct and mis-selling.';
ALTER TABLE complaints ALTER COLUMN repeat_complainant COMMENT 'TRUE when this customer has complained before. Repeat complainants indicate unresolved root causes.';
ALTER TABLE complaints ALTER COLUMN complaint_text COMMENT 'Free-text description of the complaint as recorded by the agent.';

CREATE OR REPLACE TABLE upi_disputes AS
SELECT * FROM read_files(
  '/Volumes/${CATALOG}/${SCHEMA}//seed/upi_disputes.csv',
  format => 'csv', header => true, inferSchema => true);

COMMENT ON TABLE upi_disputes IS
  'UPI transaction disputes and their resolution path. Auto-refund reflects the NPCI rule that timed-out or declined UPI transactions are reversed within 30 seconds. A switch degradation on 2026-06-14 and 2026-06-15 produced roughly ten times normal dispute volume and collapsed the auto-refund rate.';
ALTER TABLE upi_disputes ALTER COLUMN dispute_id COMMENT 'Dispute identifier, primary key.';
ALTER TABLE upi_disputes ALTER COLUMN txn_date COMMENT 'Date of the disputed UPI transaction.';
ALTER TABLE upi_disputes ALTER COLUMN raised_date COMMENT 'Date the dispute was raised by the customer.';
ALTER TABLE upi_disputes ALTER COLUMN customer_id COMMENT 'Customer who raised the dispute.';
ALTER TABLE upi_disputes ALTER COLUMN branch_id COMMENT 'Branch the customer belongs to.';
ALTER TABLE upi_disputes ALTER COLUMN txn_amount COMMENT 'Disputed transaction amount in INR.';
ALTER TABLE upi_disputes ALTER COLUMN failure_reason COMMENT 'Why the transaction failed: "Timeout at beneficiary bank", "Beneficiary bank declined", "Insufficient balance", "Invalid VPA", "Switch degradation", "Debit success credit pending", or "Duplicate submission".';
ALTER TABLE upi_disputes ALTER COLUMN resolution_path COMMENT 'How the dispute was handled: Auto-refund, Manual investigation, Chargeback raised, or Merchant recovery.';
ALTER TABLE upi_disputes ALTER COLUMN auto_refunded COMMENT 'TRUE when the dispute was resolved automatically without manual intervention. The auto-refund rate is the key operational efficiency metric here.';
ALTER TABLE upi_disputes ALTER COLUMN resolution_seconds COMMENT 'Seconds taken to resolve. Auto-refunds resolve within 30 seconds; manual investigation takes hours to days.';
ALTER TABLE upi_disputes ALTER COLUMN status COMMENT 'Open or Closed.';
ALTER TABLE upi_disputes ALTER COLUMN psp_handle COMMENT 'UPI payment service provider handle used, e.g. @indus, @okaxis, @ybl, @paytm.';

CREATE OR REPLACE TABLE chargebacks AS
SELECT * FROM read_files(
  '/Volumes/${CATALOG}/${SCHEMA}//seed/chargebacks.csv',
  format => 'csv', header => true, inferSchema => true);

COMMENT ON TABLE chargebacks IS
  'Card chargeback cases with reason code, liability assignment and outcome. Use for card dispute win-rate and fraud-loss questions.';
ALTER TABLE chargebacks ALTER COLUMN chargeback_id COMMENT 'Chargeback case identifier, primary key.';
ALTER TABLE chargebacks ALTER COLUMN txn_date COMMENT 'Date of the disputed card transaction.';
ALTER TABLE chargebacks ALTER COLUMN raised_date COMMENT 'Date the chargeback was raised.';
ALTER TABLE chargebacks ALTER COLUMN customer_id COMMENT 'Cardholder.';
ALTER TABLE chargebacks ALTER COLUMN card_type COMMENT 'Credit, Debit, or Prepaid.';
ALTER TABLE chargebacks ALTER COLUMN merchant_category COMMENT 'Merchant category, e.g. Airlines, E-commerce, Fuel, Gaming, Subscription.';
ALTER TABLE chargebacks ALTER COLUMN txn_amount COMMENT 'Disputed amount in INR.';
ALTER TABLE chargebacks ALTER COLUMN reason_code COMMENT 'Network reason code description, e.g. "Fraud - card not present", "Goods not received", "Duplicate processing".';
ALTER TABLE chargebacks ALTER COLUMN liability COMMENT 'Which party bears the loss: Bank or Merchant.';
ALTER TABLE chargebacks ALTER COLUMN status COMMENT 'Case outcome: Won, Lost, Open, or Withdrawn. Win rate is Won divided by the count of resolved cases (Won plus Lost).';
ALTER TABLE chargebacks ALTER COLUMN days_open COMMENT 'Days the case has been or was open.';
ALTER TABLE chargebacks ALTER COLUMN recovered_amount COMMENT 'Amount in INR recovered. Zero unless the case was won.';

CREATE OR REPLACE TABLE sla_tracker AS
SELECT * FROM read_files(
  '/Volumes/${CATALOG}/${SCHEMA}//seed/sla_tracker.csv',
  format => 'csv', header => true, inferSchema => true);

COMMENT ON TABLE sla_tracker IS
  'Pre-aggregated monthly complaint SLA performance by branch and RBI category. PREFER THIS TABLE over raw complaints for trend and SLA-breach-rate questions: it is already aggregated, so results stay small and cannot be silently truncated.';
ALTER TABLE sla_tracker ALTER COLUMN report_month COMMENT 'Reporting month, first day of month. Latest is 2026-08-01.';
ALTER TABLE sla_tracker ALTER COLUMN branch_id COMMENT 'Branch code.';
ALTER TABLE sla_tracker ALTER COLUMN region COMMENT 'Region, denormalised for regional roll-ups without a join.';
ALTER TABLE sla_tracker ALTER COLUMN rbi_category COMMENT 'RBI Ombudsman ground of complaint.';
ALTER TABLE sla_tracker ALTER COLUMN complaints_received COMMENT 'Complaints received in the month for this branch and category.';
ALTER TABLE sla_tracker ALTER COLUMN complaints_resolved COMMENT 'Complaints resolved in the month.';
ALTER TABLE sla_tracker ALTER COLUMN within_sla COMMENT 'Count resolved within the SLA.';
ALTER TABLE sla_tracker ALTER COLUMN breached_sla COMMENT 'Count resolved outside the SLA. SLA breach rate is breached_sla divided by complaints_resolved.';
ALTER TABLE sla_tracker ALTER COLUMN avg_days_to_resolve COMMENT 'Average calendar days to resolve in the month.';
ALTER TABLE sla_tracker ALTER COLUMN ombudsman_escalations COMMENT 'Count escalated to the RBI Ombudsman in the month.';

-- ===========================================================================
-- RM PERFORMANCE AND INCENTIVES  (Genie agent 3)
-- ===========================================================================

CREATE OR REPLACE TABLE relationship_managers AS
SELECT * FROM read_files(
  '/Volumes/${CATALOG}/${SCHEMA}//seed/relationship_managers.csv',
  format => 'csv', header => true, inferSchema => true);

COMMENT ON TABLE relationship_managers IS
  'Relationship manager dimension. One row per RM, 180 RMs. Join on rm_id.';
ALTER TABLE relationship_managers ALTER COLUMN rm_id COMMENT 'Relationship manager identifier, primary key. Format RMnnnn.';
ALTER TABLE relationship_managers ALTER COLUMN rm_name COMMENT 'RM full name.';
ALTER TABLE relationship_managers ALTER COLUMN branch_id COMMENT 'Branch the RM is posted at.';
ALTER TABLE relationship_managers ALTER COLUMN region COMMENT 'Region.';
ALTER TABLE relationship_managers ALTER COLUMN zone COMMENT 'Branch zone: Metro, Urban, Semi-Urban, Rural.';
ALTER TABLE relationship_managers ALTER COLUMN rm_grade COMMENT 'Seniority grade: Junior, Mid, Senior, or Lead. Grade determines the incentive slab grid and target size.';
ALTER TABLE relationship_managers ALTER COLUMN date_joined COMMENT 'Date the RM joined the bank.';
ALTER TABLE relationship_managers ALTER COLUMN portfolio_count COMMENT 'Number of customers in the RM portfolio.';
ALTER TABLE relationship_managers ALTER COLUMN active_flag COMMENT 'TRUE when the RM is currently employed and active.';

CREATE OR REPLACE TABLE incentive_slabs AS
SELECT * FROM read_files(
  '/Volumes/${CATALOG}/${SCHEMA}//seed/incentive_slabs.csv',
  format => 'csv', header => true, inferSchema => true);

COMMENT ON TABLE incentive_slabs IS
  'Incentive slab grid by RM grade. Defines the payout multiple for each attainment band and the product-mix quality gate that must be cleared before a full payout is released.';
ALTER TABLE incentive_slabs ALTER COLUMN slab_id COMMENT 'Slab identifier, primary key.';
ALTER TABLE incentive_slabs ALTER COLUMN rm_grade COMMENT 'RM grade the slab applies to.';
ALTER TABLE incentive_slabs ALTER COLUMN attainment_from_pct COMMENT 'Lower bound of the attainment band, inclusive, as a percentage.';
ALTER TABLE incentive_slabs ALTER COLUMN attainment_to_pct COMMENT 'Upper bound of the attainment band, exclusive, as a percentage.';
ALTER TABLE incentive_slabs ALTER COLUMN payout_pct_of_target COMMENT 'Payout multiple applied to the target incentive for this band. 1.00 means a full payout, 1.60 means 160 percent.';
ALTER TABLE incentive_slabs ALTER COLUMN quality_gate_required COMMENT 'TRUE when this band requires the product-mix quality gate to be cleared. Applies at full payout and above.';
ALTER TABLE incentive_slabs ALTER COLUMN min_product_mix_score COMMENT 'Minimum product_mix_score needed to clear the quality gate for this band. Zero when no gate applies.';

CREATE OR REPLACE TABLE rm_targets AS
SELECT * FROM read_files(
  '/Volumes/${CATALOG}/${SCHEMA}//seed/rm_targets.csv',
  format => 'csv', header => true, inferSchema => true);

COMMENT ON TABLE rm_targets IS
  'Monthly RM targets by product line. Grain is target_month x rm_id. Join to rm_achievement on the same grain to compute attainment.';
ALTER TABLE rm_targets ALTER COLUMN target_month COMMENT 'Target month, first day of month.';
ALTER TABLE rm_targets ALTER COLUMN rm_id COMMENT 'Relationship manager identifier.';
ALTER TABLE rm_targets ALTER COLUMN branch_id COMMENT 'Branch code.';
ALTER TABLE rm_targets ALTER COLUMN region COMMENT 'Region.';
ALTER TABLE rm_targets ALTER COLUMN rm_grade COMMENT 'RM grade.';
ALTER TABLE rm_targets ALTER COLUMN target_casa_amount COMMENT 'CASA target in INR. CASA means Current Account and Savings Account balances.';
ALTER TABLE rm_targets ALTER COLUMN target_loan_amount COMMENT 'Loan disbursal target in INR.';
ALTER TABLE rm_targets ALTER COLUMN target_cards COMMENT 'Target count of new credit cards sourced.';
ALTER TABLE rm_targets ALTER COLUMN target_insurance COMMENT 'Target count of insurance policies sold.';
ALTER TABLE rm_targets ALTER COLUMN target_product_mix_score COMMENT 'Target product-mix score, 0 to 1. Measures balance across product lines rather than volume in one.';

CREATE OR REPLACE TABLE rm_achievement AS
SELECT * FROM read_files(
  '/Volumes/${CATALOG}/${SCHEMA}//seed/rm_achievement.csv',
  format => 'csv', header => true, inferSchema => true);

COMMENT ON TABLE rm_achievement IS
  'Monthly RM achievement, attainment and incentive earned. THIS IS THE PRIMARY TABLE for RM performance and incentive questions. A cohort of roughly 21 RMs over-attains on volume while carrying a weak product mix; their quality gate fails and clawback_flag is set, so incentive paid diverges from portfolio quality.';
ALTER TABLE rm_achievement ALTER COLUMN achievement_month COMMENT 'Achievement month, first day of month. Latest is 2026-08-01.';
ALTER TABLE rm_achievement ALTER COLUMN rm_id COMMENT 'Relationship manager identifier. Join to relationship_managers.';
ALTER TABLE rm_achievement ALTER COLUMN branch_id COMMENT 'Branch code.';
ALTER TABLE rm_achievement ALTER COLUMN region COMMENT 'Region.';
ALTER TABLE rm_achievement ALTER COLUMN rm_grade COMMENT 'RM grade.';
ALTER TABLE rm_achievement ALTER COLUMN actual_casa_amount COMMENT 'CASA balances actually sourced in INR.';
ALTER TABLE rm_achievement ALTER COLUMN actual_loan_amount COMMENT 'Loans actually disbursed in INR.';
ALTER TABLE rm_achievement ALTER COLUMN actual_cards COMMENT 'Credit cards actually sourced.';
ALTER TABLE rm_achievement ALTER COLUMN actual_insurance COMMENT 'Insurance policies actually sold. A low value alongside high CASA and loan volume is the signature of a distorted product mix.';
ALTER TABLE rm_achievement ALTER COLUMN product_mix_score COMMENT 'Product-mix quality score, 0 to 1. Below 0.50 indicates volume concentrated in one or two products. This is the quality gate input.';
ALTER TABLE rm_achievement ALTER COLUMN attainment_pct COMMENT 'Overall attainment as a percentage, the average of CASA attainment and loan attainment. 100 means target met exactly.';
ALTER TABLE rm_achievement ALTER COLUMN incentive_earned COMMENT 'Incentive earned in INR for the month, after applying the slab payout multiple and the quality gate.';
ALTER TABLE rm_achievement ALTER COLUMN quality_gate_passed COMMENT 'TRUE when product_mix_score cleared the minimum required by the attainment slab. FALSE means the payout was reduced.';
ALTER TABLE rm_achievement ALTER COLUMN clawback_flag COMMENT 'TRUE when the RM attained a full-payout band but failed the quality gate, so part of the incentive is subject to clawback. Use this to find incentive distortion.';

CREATE OR REPLACE TABLE customer_portfolio AS
SELECT * FROM read_files(
  '/Volumes/${CATALOG}/${SCHEMA}//seed/customer_portfolio.csv',
  format => 'csv', header => true, inferSchema => true);

COMMENT ON TABLE customer_portfolio IS
  'Customer master with the owning relationship manager, segment, relationship value and churn risk. Join on customer_id to reach complaints or loans, and on rm_id to reach RM performance.';
ALTER TABLE customer_portfolio ALTER COLUMN customer_id COMMENT 'Customer identifier, primary key. Format CUnnnnnn.';
ALTER TABLE customer_portfolio ALTER COLUMN rm_id COMMENT 'Relationship manager who owns this customer.';
ALTER TABLE customer_portfolio ALTER COLUMN branch_id COMMENT 'Home branch.';
ALTER TABLE customer_portfolio ALTER COLUMN region COMMENT 'Region.';
ALTER TABLE customer_portfolio ALTER COLUMN customer_segment COMMENT 'Wealth segment: Mass, Mass Affluent, Affluent, Private, or MSME.';
ALTER TABLE customer_portfolio ALTER COLUMN relationship_start COMMENT 'Date the customer relationship began.';
ALTER TABLE customer_portfolio ALTER COLUMN total_relationship_value COMMENT 'Total relationship value in INR across all products.';
ALTER TABLE customer_portfolio ALTER COLUMN products_held COMMENT 'Count of distinct products the customer holds. Low counts are cross-sell opportunities.';
ALTER TABLE customer_portfolio ALTER COLUMN casa_balance COMMENT 'Current and savings account balance in INR.';
ALTER TABLE customer_portfolio ALTER COLUMN risk_rating COMMENT 'Internal credit risk rating: Low, Medium, or High.';
ALTER TABLE customer_portfolio ALTER COLUMN nri_flag COMMENT 'TRUE when the customer is a Non-Resident Indian.';
ALTER TABLE customer_portfolio ALTER COLUMN churn_risk_score COMMENT 'Modelled churn probability, 0 to 1. Above 0.7 warrants retention action.';

CREATE OR REPLACE TABLE product_holdings AS
SELECT * FROM read_files(
  '/Volumes/${CATALOG}/${SCHEMA}//seed/product_holdings.csv',
  format => 'csv', header => true, inferSchema => true);

COMMENT ON TABLE product_holdings IS
  'One row per product a customer holds. Use for cross-sell gap analysis: compare products held against the full product_master list for a segment.';
ALTER TABLE product_holdings ALTER COLUMN holding_id COMMENT 'Holding identifier, primary key.';
ALTER TABLE product_holdings ALTER COLUMN customer_id COMMENT 'Customer identifier.';
ALTER TABLE product_holdings ALTER COLUMN rm_id COMMENT 'Relationship manager who owns the customer.';
ALTER TABLE product_holdings ALTER COLUMN product_code COMMENT 'Product held. Join to product_master.';
ALTER TABLE product_holdings ALTER COLUMN opened_date COMMENT 'Date the product was opened.';
ALTER TABLE product_holdings ALTER COLUMN balance_or_limit COMMENT 'Balance for deposits or credit limit for lending products, in INR.';
ALTER TABLE product_holdings ALTER COLUMN is_active COMMENT 'TRUE when the holding is currently active.';
ALTER TABLE product_holdings ALTER COLUMN cross_sell_eligible COMMENT 'TRUE when the customer is eligible for cross-sell on this relationship.';
