-- Genie Control Tower — Lakebase (Postgres) schema.
--
-- This is the WRITE plane. It exists because Genie must never write: Genie generates SQL from
-- untrusted natural language, so its run-as identity holds SELECT only. Anything that changes the
-- world lands here first as a PROPOSAL, gets a human decision, and only then executes through a
-- Unity-Catalog-governed connector.
--
-- Four things a bank auditor can reconstruct from these tables alone:
--   1. WHO asked the question that produced an action        (actions.session_uuid -> agent_sessions)
--   2. WHAT the model actually saw when it proposed it       (actions.trace_id -> MLflow trace)
--   3. WHICH control passed or blocked it, and on what authority (action_events + action_policies.legal_basis)
--   4. WHO approved it, and that it was not the proposer     (actions.requested_by vs approved_by)

CREATE SCHEMA IF NOT EXISTS ${LAKEBASE_SCHEMA};
SET search_path TO ${LAKEBASE_SCHEMA};

-- ---------------------------------------------------------------------------
-- actions — one row per proposed change to the world
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS actions (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent          TEXT NOT NULL,                    -- which agent proposed it
    action_type    TEXT NOT NULL,                    -- joins action_policies
    subject        TEXT NOT NULL,                    -- loan account / complaint / RM the action is about
    payload        JSONB NOT NULL DEFAULT '{}'::jsonb,
    status         TEXT NOT NULL DEFAULT 'proposed',
    level          INTEGER NOT NULL DEFAULT 2,       -- autonomy rung: 1 advise .. 4 auto-execute
    region         TEXT,                             -- North/South/East/West/Central
    branch_id      TEXT,

    -- WHEN the action is to take effect. First-class (not buried in payload) because the RBI
    -- conduct-hours guardrail keys on it and auditors query it directly.
    scheduled_at   TIMESTAMPTZ,

    -- Provenance back to the traced conversation turn that produced this proposal.
    session_uuid   TEXT,
    trace_id       TEXT,

    requested_by   TEXT NOT NULL,                    -- the proposer (the agent)
    approved_by    TEXT,                             -- the human (never the proposer)
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    decided_at     TIMESTAMPTZ,
    executed_at    TIMESTAMPTZ,
    result         JSONB,
    external_ref   TEXT                              -- id in the downstream bank system
);

-- ---------------------------------------------------------------------------
-- action_events — append-only lineage. Never updated, never deleted.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS action_events (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action_id  BIGINT NOT NULL REFERENCES actions(id),
    ts         TIMESTAMPTZ NOT NULL DEFAULT now(),
    event      TEXT NOT NULL,                        -- proposed|approved|rejected|executing|executed|failed|escalated|guardrail|connector
    actor      TEXT NOT NULL,
    detail     JSONB
);

-- ---------------------------------------------------------------------------
-- action_policies — the guardrails, as DATA. One row per action type.
--
-- Every rule here is a technical control, not a sentence in a prompt asking the model to behave.
-- `legal_basis` makes each verdict self-documenting: when a control blocks an action the UI can
-- show the regulation it implements, which is the difference between "the app said no" and
-- "this is refused under the RBI Fair Practices Code".
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS action_policies (
    action_type                  TEXT PRIMARY KEY,
    domain                       TEXT NOT NULL,        -- COLLECTIONS | GRIEVANCE | RM
    description                  TEXT NOT NULL,

    -- Value limits (INR — this is an Indian bank; the scaffold's EUR caps are gone).
    max_amount_inr               NUMERIC(16,2),
    allowed_regions              TEXT[],

    -- Approval ladder.
    requires_approval            BOOLEAN NOT NULL DEFAULT TRUE,
    approver_role                TEXT,                 -- role that must sign off
    max_autonomy_level           INTEGER NOT NULL DEFAULT 2,

    -- Conduct controls. These are the ones that matter to a bank, and each is VERIFIED AGAINST
    -- UNITY CATALOG at evaluate() time rather than trusted from the model's payload.
    rbi_conduct_hours            BOOLEAN NOT NULL DEFAULT FALSE, -- contact only 08:00-19:00 IST
    requires_agent_certification BOOLEAN NOT NULL DEFAULT FALSE, -- agent must be conduct-certified
    blocked_by_open_grievance    BOOLEAN NOT NULL DEFAULT FALSE, -- no recovery pressure while a complaint is open
    min_dpd_days                 INTEGER,                        -- field recovery floor
    max_contacts_per_day         INTEGER,                        -- anti-harassment contact cap

    legal_basis                  TEXT
);

-- ---------------------------------------------------------------------------
-- agent_sessions — conversation memory, and the join key from an action back to
-- the question, the SQL and the MLflow trace that produced it.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS agent_sessions (
    session_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_uuid   TEXT NOT NULL UNIQUE,
    user_email     TEXT NOT NULL,
    persona        TEXT,
    question       TEXT,
    routed_domains TEXT,
    fused_answer   TEXT,
    trace_id       TEXT,                              -- MLflow 3 trace for this turn
    latency_ms     INTEGER,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS agent_feedback (
    feedback_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_uuid TEXT NOT NULL,
    user_email   TEXT NOT NULL,
    rating       INTEGER NOT NULL,                    -- +1 / -1
    comment      TEXT,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- runtime_flags — the kill switch.
--
-- A single-row table the executor reads before every external call. An AI CoE that cannot stop its
-- agents without a redeploy does not control them, so stopping is a data change, not a code change.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS runtime_flags (
    flag        TEXT PRIMARY KEY,
    enabled     BOOLEAN NOT NULL,
    reason      TEXT,
    changed_by  TEXT,
    changed_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

INSERT INTO runtime_flags (flag, enabled, reason, changed_by) VALUES
    ('actions_enabled',   TRUE, 'normal operation', 'workshop-setup'),
    ('autonomy_enabled',  TRUE, 'L4 auto-approve permitted within policy', 'workshop-setup')
ON CONFLICT (flag) DO NOTHING;

-- ---------------------------------------------------------------------------
-- Indexes for the queue view and the audit queries.
-- ---------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_actions_status       ON actions(status);
CREATE INDEX IF NOT EXISTS idx_actions_agent        ON actions(agent);
CREATE INDEX IF NOT EXISTS idx_actions_session      ON actions(session_uuid);
CREATE INDEX IF NOT EXISTS idx_actions_created      ON actions(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_action_events_action ON action_events(action_id);
CREATE INDEX IF NOT EXISTS idx_sessions_uuid        ON agent_sessions(session_uuid);
CREATE INDEX IF NOT EXISTS idx_feedback_session     ON agent_feedback(session_uuid);
